<?php

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    header('Allow: POST');
    exit('Method not allowed.');
}

$batchId = isset($_POST['batch_id']) ? (int)$_POST['batch_id'] : 0;

if ($batchId <= 0) {
    exit('Invalid batch ID.');
}

$config = require __DIR__ . '/../app/config.php';
$pdo = require __DIR__ . '/../app/db.php';

$batchStmt = $pdo->prepare("
    SELECT stored_filename
    FROM cdr_import_batches
    WHERE id = :id
");

$batchStmt->execute([
    ':id' => $batchId,
]);

$batch = $batchStmt->fetch(PDO::FETCH_ASSOC);

if (!$batch) {
    header('Location: /results.php');
    exit;
}

// Uploaded filenames are generated by the application. Keep this boundary
// explicit so a corrupted database value cannot escape the configured directory.
$storedFilename = (string)$batch['stored_filename'];

if ($storedFilename !== basename($storedFilename)) {
    exit('Invalid stored filename.');
}

$filePath = rtrim($config['upload_dir'], '/\\') . DIRECTORY_SEPARATOR . $storedFilename;

if (file_exists($filePath) && !unlink($filePath)) {
    exit('Could not delete uploaded file.');
}

// The schema cascades this single batch deletion into its normalized CDRs,
// materialized findings, and finding-call links.
$delete = $pdo->prepare("
    DELETE FROM cdr_import_batches
    WHERE id = :id
");

$delete->execute([
    ':id' => $batchId,
]);

header('Location: /results.php');
exit;
